---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

version: '3.7'

services:
  dnsmasq:
    build:
      context: '.'
    image: 'mireiawen/dnsmasq:latest'
    restart: 'always'
    volumes:
    - type: 'volume'
      source: 'config'
      target: '/etc/dnsmasq'
    network_mode: 'bridge'
    hostname: '$HOSTNAME.$DOMAIN'
    container_name: 'dnsmasq'
    ports:
    - target: 53
      published: '$HOST:53'
      protocol: 'udp'
      mode: 'host'
    - target: 53
      published: '$HOST:53'
      protocol: 'tcp'
      mode: 'host'
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.dnsmasq.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.dnsmasq.entrypoints=web'
    - 'traefik.http.routers.dnsmasq.middlewares=dnsmasq-whitelist,http-to-https'
    - 'traefik.http.routers.dnsmasq.service=dnsmasq'
    - 'traefik.http.routers.dnsmasq-secure.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.dnsmasq-secure.entrypoints=websecure'
    - 'traefik.http.routers.dnsmasq-secure.middlewares=dnsmasq-whitelist'
    - 'traefik.http.routers.dnsmasq-secure.service=dnsmasq'
    - 'traefik.http.middlewares.dnsmasq-whitelist.ipwhitelist.sourcerange=$NETWORKS'
    - 'traefik.http.services.dnsmasq.loadbalancer.passhostheader=true'
    - 'traefik.http.services.dnsmasq.loadbalancer.server.port=8080'

volumes:
  config: {}
