---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

version: '3.7'

services:
  dnsmasq:
    build:
      context: '.'
    image: 'mireiawen/dnsmasq:latest'
    restart: 'always'
    networks:
    - 'traefik'
    volumes:
    - type: 'volume'
      source: 'config'
      target: '/etc/dnsmasq'
    container_name: 'dnsmasq'
    ports:
    - '$HOST:53:53/udp'
    - '$HOST:53:53/tcp'
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.dnsmasq.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.dnsmasq.entrypoints=web'
    - 'traefik.http.routers.dnsmasq.middlewares=whitelist@file,http-to-https@file'
    - 'traefik.http.routers.dnsmasq.service=dnsmasq'
    - 'traefik.http.routers.dnsmasq-secure.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.dnsmasq-secure.entrypoints=websecure'
    - 'traefik.http.routers.dnsmasq-secure.middlewares=whitelist@file'
    - 'traefik.http.routers.dnsmasq-secure.service=dnsmasq'
    - 'traefik.http.services.dnsmasq.loadbalancer.passhostheader=true'
    - 'traefik.http.services.dnsmasq.loadbalancer.server.port=8080'

volumes:
  config: {}

networks:
  traefik:
    external: true
